# Generated by Django 4.2.4 on 2023-09-06 15:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=150)),
                ('About', models.CharField(max_length=1000)),
                ('Media', models.ImageField(default='', upload_to='uploads/')),
                ('Age', models.CharField(default='', max_length=100)),
                ('State', models.CharField(default='', max_length=100)),
                ('Username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'group_tbl',
            },
        ),
        migrations.CreateModel(
            name='GroupSoilTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupSoilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilTagging', to='group.group_tbl')),
                ('soilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.soiltag')),
            ],
            options={
                'unique_together': {('GroupSoilTag', 'soilTag')},
            },
        ),
        migrations.CreateModel(
            name='GroupPlantTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupPlantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantTagging', to='group.group_tbl')),
                ('plantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.planttag')),
            ],
            options={
                'unique_together': {('GroupPlantTag', 'plantTag')},
            },
        ),
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joined_on', models.DateTimeField(auto_now_add=True)),
                ('GroupMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('GroupName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group_tbl')),
            ],
            options={
                'unique_together': {('GroupName', 'GroupMember')},
            },
        ),
    ]
