# Generated by Django 4.2.4 on 2023-09-06 15:13

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='prodProduct',
            fields=[
                ('productid', models.AutoField(primary_key=True, serialize=False)),
                ('productName', models.CharField(blank=True, max_length=255)),
                ('productDesc', models.CharField(blank=True, max_length=1500)),
                ('productCategory', models.CharField(blank=True, max_length=255)),
                ('productPrice', models.DecimalField(decimal_places=2, max_digits=4)),
                ('productStock', models.IntegerField(default=0)),
                ('productPhoto', models.ImageField(null=True, upload_to='images/')),
                ('productRating', models.IntegerField(default=0)),
                ('timePosted', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'prodProduct',
            },
        ),
    ]
