# Generated by Django 4.1.6 on 2023-02-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prodproduct',
            name='productPhoto',
            field=models.ImageField(null=True, upload_to='media/images/'),
        ),
    ]
