# Generated by Django 4.2.4 on 2023-09-06 15:14

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import member.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('Email', models.CharField(max_length=150, unique=True)),
                ('Username', models.CharField(max_length=150)),
                ('Name', models.CharField(max_length=150)),
                ('DateOfBirth', models.CharField(max_length=150)),
                ('Age', models.IntegerField()),
                ('District', models.CharField(max_length=150)),
                ('State', models.CharField(max_length=150)),
                ('Occupation', models.CharField(max_length=150)),
                ('About', models.CharField(max_length=150)),
                ('Gender', models.CharField(max_length=1)),
                ('MaritalStatus', models.CharField(max_length=150)),
                ('UserLevel', models.CharField(max_length=10)),
                ('Photo', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'login_person',
            },
        ),
        migrations.CreateModel(
            name='Plants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pictures', models.ImageField(upload_to='uploads/')),
                ('Species', models.CharField(max_length=150)),
                ('Types', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'Plants',
            },
        ),
        migrations.CreateModel(
            name='PlantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlantTagName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'PlantTag',
            },
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Detail', models.CharField(max_length=255)),
                ('Name', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'SensorData',
            },
        ),
        migrations.CreateModel(
            name='SoilTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SoilTagName', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'SoilTag',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('ranking', models.FloatField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to=member.models.Users.upload_photo)),
                ('resume', models.ImageField(blank=True, null=True, upload_to=member.models.Users.upload_file)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member1', to=settings.AUTH_USER_MODEL)),
                ('member2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='member2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField()),
                ('date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('sender', models.CharField(max_length=255)),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.room')),
            ],
        ),
        migrations.CreateModel(
            name='MemberRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_user', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('to_user', 'from_user')},
            },
        ),
        migrations.CreateModel(
            name='Memberlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatRoom', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='member.room')),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_person', to=settings.AUTH_USER_MODEL)),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_person', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('from_person', 'to_person')},
            },
        ),
    ]
