# Generated by Django 4.1.3 on 2022-12-15 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_plants_planttag_sensordata_soiltag_users_room_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
