# Generated by Django 4.1.6 on 2023-02-04 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='Photo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
