# Generated by Django 4.1.5 on 2023-01-31 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0004_alter_person_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=150)),
            ],
            options={
                'db_table': 'approvedTopic',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=150)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
            ],
            options={
                'db_table': 'Topic',
            },
        ),
        migrations.CreateModel(
            name='SuggestedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TopicName', models.CharField(max_length=150)),
                ('Person_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
            ],
            options={
                'db_table': 'suggestedTopic',
            },
        ),
    ]
