# Generated by Django 4.2.4 on 2024-03-31 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_order_seller_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='seller_id',
            new_name='seller',
        ),
    ]
