# Generated by Django 4.1.3 on 2022-12-15 01:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('group', '0001_initial'),
        ('member', '0003_plants_planttag_sensordata_soiltag_users_room_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=255)),
                ('Message', models.CharField(max_length=255)),
                ('Skill', models.CharField(default='', max_length=20)),
                ('State', models.CharField(default='', max_length=100)),
                ('Photo', models.ImageField(blank=True, default='', null=True, upload_to='uploads/')),
                ('Video', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('created_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('Group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group_tbl')),
            ],
            options={
                'db_table': 'Feed',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.TextField()),
                ('Pictures', models.ImageField(null=True, upload_to='uploads/')),
                ('Video', models.FileField(null=True, upload_to='uploads/')),
                ('Commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('Feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sharing.feed')),
            ],
            options={
                'db_table': 'Comment',
            },
        ),
        migrations.CreateModel(
            name='FeedSoilTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedSoilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soilTagging', to='sharing.feed')),
                ('soilTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.soiltag')),
            ],
            options={
                'unique_together': {('FeedSoilTag', 'soilTag')},
            },
        ),
        migrations.CreateModel(
            name='FeedPlantTagging',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedPlantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plantTagging', to='sharing.feed')),
                ('plantTag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.planttag')),
            ],
            options={
                'unique_together': {('FeedPlantTag', 'plantTag')},
            },
        ),
    ]
