# Generated by Django 4.1.3 on 2022-12-15 03:57

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_plants_planttag_sensordata_soiltag_users_room_and_more'),
        ('group', '0001_initial'),
        ('sharing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feed',
            name='Group',
        ),
        migrations.CreateModel(
            name='GroupTimelineComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GrpMessage', models.TextField()),
                ('GrpPictures', models.ImageField(null=True, upload_to='uploads/')),
                ('GrpVideo', models.FileField(null=True, upload_to='uploads/')),
                ('GrpCommenterFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('GrpFeedFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groupcomments', to='sharing.feed')),
            ],
            options={
                'db_table': 'GroupTimelineComment',
            },
        ),
        migrations.CreateModel(
            name='GroupTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('GroupTitle', models.CharField(max_length=255)),
                ('GroupMessage', models.CharField(max_length=255)),
                ('GroupSkill', models.CharField(default='', max_length=20)),
                ('GroupState', models.CharField(default='', max_length=100)),
                ('GroupPhoto', models.ImageField(blank=True, default='', null=True, upload_to='uploads/')),
                ('GroupVideo', models.FileField(blank=True, default='', null=True, upload_to='uploads/')),
                ('Groupcreated_at', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('CreatorFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('GroupFK', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='group.group_tbl')),
            ],
            options={
                'db_table': 'GroupTimeline',
            },
        ),
    ]
