# Generated by Django 4.1.3 on 2022-12-19 02:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_alter_person_photo'),
        ('sharing', '0002_remove_feed_group_grouptimelinecomment_grouptimeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Like', models.IntegerField()),
                ('Commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.person')),
                ('Feed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='sharing.feed')),
            ],
            options={
                'db_table': 'Likes',
            },
        ),
    ]
