# Generated by Django 4.1.3 on 2022-12-19 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0003_likes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='likes',
            old_name='Commenter',
            new_name='Liker',
        ),
    ]
