# Generated by Django 4.1.3 on 2022-12-19 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sharing', '0004_rename_commenter_likes_liker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='Like',
        ),
    ]
